[package]
name = "punctum-air"
version = "0.1.0"
edition = "2021"

[dependencies]
punctum-vm = { path = "../vm" }
p3-air = { workspace = true }
p3-challenger = { workspace = true }
p3-circle = { workspace = true }
p3-commit = { workspace = true }
p3-field = { workspace = true }
p3-fri = { workspace = true }
p3-keccak = { workspace = true }
p3-matrix = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-mersenne-31 = { workspace = true }
p3-symmetric = { workspace = true }
p3-uni-stark = { workspace = true }
p3-batch-stark = { workspace = true }
p3-lookup = { workspace = true }
